databases:
  - name: controle-agua-db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: controle-agua
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt; python manage.py collectstatic --noinput; python manage.py migrate; python manage.py create_superuser_if_missing"
    startCommand: "gunicorn hidrometro_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DB_CONN_MAX_AGE
        value: "60"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: controle-agua-db
          property: connectionString
